### ISSUE TITLE
Page down / clone not possible

### ISSUE THREAD

**Issue by dtrywets** [pawelszydlo/fis-designer#1]
Dear Pawel, happy new year and thanks a lot for your amazing work on this. 
Sadly the page seems to be down. I hope this is just for maintanance reasons. 

I tried cloning the project to my webspace but somehow it seems there's a folder missing. 
Running deploy.sh it's telling me this: 

```
./deploy.sh
Syncing control units...
./deploy.sh: line 4: cd: src/assets/js/FIS-Control-binary-converter/: No such file or directory
Already up to date.
Building...
./deploy.sh: line 9: npm: command not found
Sending to DO...
./deploy.sh: line 12: cd: dist/fis-design: No such file or directory
ssh: Could not resolve hostname do: No address associated with hostname
lost connection
``` 

Having tried this on a local machine as well, it turns out like this: 
```
➜  fis-designer sudo ./deploy.sh
Syncing control units...
./deploy.sh: line 4: cd: src/assets/js/FIS-Control-binary-converter/: No such file or directory
Already up to date.
Building...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path //package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '//package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-03T08_51_37_127Z-debug-0.log
Sending to DO...
./deploy.sh: line 12: cd: dist/fis-design: No such file or directory
ssh: Could not resolve hostname do: Temporary failure in name resolution
lost connection
```
I hope that you could help working out on this problem :-) 

kind regards,
Sebastian

**Comment by pawelszydlo** [comment]
Hi Sebastian,
As for the site being down - the domain has expired. I've already taken care of that and it should be back soon.
As for the `deploy.sh` - this is just a quick script I use for deployment, it shouldn't really be included in this repo as it is not universal.

**Comment by dtrywets** [comment]
Hey Pawel,
thanks for your quick reaction. That's pretty good to hear, even if it'd been great to have it running on my local machine :-) .
Could you drop a comment here as soon as it's back online?

**Comment by pawelszydlo** [comment]
The site is already up.
As for local development: this is a standard AngularTS project, you should be able to run it without issues. 
The only "special" thing is that you have to put the [config converter](https://github.com/SBieger/FIS-Control-binary-converter) into  `src/assets/js/FIS-Control-binary-converter`.
I'll try to write a "how to run" instruction when I have time.
